const projects = [
  {
    mediaSrc: ".\\p_fenixquiz.png",
    name: "Quiz Fênix - Projeto começo Html",
    features: ["Web game", "Frontend"],
    categorie: ["webgame", "games"],
    techs: ["Html", "Css", "Git"],
    ghLink: "https://dropperdev.github.io/fenixquiz/",
    repositorieLink: "https://github.com/DropperDEV/fenixquiz",
  },
  {
    mediaSrc: ".\\p_lojafenix.png",
    name: "Loja Fênix - Projeto final Html",
    features: ["Website", "Frontend", "Design"],
    categorie: ["website", "aplication"],
    techs: ["Html", "Css", "Flexbox"],
    ghLink: "https://dropperdev.github.io/lojafenix/",
    repositorieLink: "https://github.com/DropperDEV/lojafenix",
  },
  {
    mediaSrc: ".\\p_todolist.png",
    name: "Lista de tarefas em react",
    features: ["Website", "Frontend", "React"],
    categorie: ["website"],
    techs: ["Html", "Styled-components", "React"],
    ghLink: "https://dropperdev.github.io/todoList/",
    repositorieLink: "https://github.com/DropperDEV/todoList",
  },
  {
    mediaSrc: ".\\p_cpp.png",
    name: "Prep. Programação competitiva",
    features: ["Algoritmos", "Lógica"],
    categorie: ["aplication"],
    techs: ["C++"],
    repositorieLink: "https://github.com/DropperDEV/COMPETITIVE-PROGRAMMING",
  },
  {
    mediaSrc: ".\\p_usepopcorn.png",
    name: "Usepopcorn - Projeto curso gringo",
    features: ["React", "Hooks", "JS"],
    categorie: ["website"],
    techs: ["Javascript", "React", "CSS"],
    repositorieLink: "https://github.com/DropperDEV/usepopcorn",
    ghLink: "https://dropperdev.github.io/usepopcorn/",
  },
  {
    mediaSrc: ".\\p_asteroids.png",
    name: "Asteroids - Feprocic 2023",
    features: ["GDevelop", "Low Code"],
    categorie: ["games"],
    techs: ["GDevelop", "Abstração", "JS"],
    repositorieLink: "https://github.com/DropperDEV/asteroids-web",
    ghLink: "https://dropperdev.github.io/asteroids-web/",
  },
  {
    mediaSrc: ".\\p_expresstruck.png",
    name: "Express Truck - Projeto começo React",
    features: ["Fullstack", "Banco de Dados"],
    categorie: ["website"],
    techs: ["React", "TailwindCSS", "Supabase"],
    repositorieLink: "https://github.com/DropperDEV/express-truck",
    ghLink: "https://dropperdev.github.io/express-truck/",
  },
  {
    mediaSrc: ".\\p_mathon.png",
    name: "Math On - Projeto Começo Javascript",
    features: [ "Javascript", "TailwindCSS"],
    categorie: ["website", "aplication"],
    techs: ["JS", "TailwindCSS"],
    repositorieLink: "https://github.com/DropperDEV/proj-mathon-pgweb",
    ghLink: "https://dropperdev.github.io/proj-mathon-pgweb/dist/index.html",
  },
];

export default projects;
